networks:
  airline: {}

volumes:
  mysql-data: {}
  airline-target: {}

services:
  airline-frontend:
    image: airline-app:v4
    container_name: airline-frontend
    depends_on:
      - airline-db
    environment:
      DB_HOST: airline-db
      ES_HOST: airline-search
    entrypoint: sh -c "/home/airline/airline/scripts/data/init.sh && /home/airline/airline/scripts/web/start.sh"
    ports:
      - "9001:9001"
    networks:
      - airline

  airline-backend:
    image: airline-app:v4
    container_name: airline-backend
    depends_on:
      - airline-db
    environment:
      DB_HOST: airline-db
      ES_HOST: airline-search
    entrypoint: sh -c "/home/airline/airline/scripts/data/init.sh && /home/airline/airline/scripts/data/start.sh"
    ports:
      - "9000:9000"
    networks:
      - airline

  airline-db:
    image: bitnami/mysql:8.0
    container_name: airline-db
    environment:
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - "33063:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - airline

  airline-search:
    image: elasticsearch:7.17.21
    container_name: airline-search
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
    networks:
      - airline
