networks:
  airline: {}

volumes:
  mysql-data: {}
  airline-target: {}

services:
  airline-app:
    container_name: airline-app
    image: airline-app:v3.1
    depends_on:
      - airline-db
    environment:
      DB_HOST: airline-db
      ES_HOST: airline-search
    entrypoint: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ".:/home/airline/airline"
      - "./.docker/data/init.sh:/home/airline/init-data.sh"
      - "./.docker/data/start.sh:/home/airline/start-data.sh"
      - "./.docker/web/start.sh:/home/airline/start-web.sh"
      - "./.docker/web/clean.sh:/home/airline/clean-web.sh"
    #    ports:
    #      - "9000:9000"
    healthcheck:
      test: curl --fail http://localhost:9000/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - airline

  airline-db:
    image: bitnami/mysql:8.0
    container_name: airline-db
    environment:
      MYSQL_CHARACTER_SET: utf8mb4
      MYSQL_COLLATE: utf8mb4_unicode_ci
      ALLOW_EMPTY_PASSWORD: yes
    #    ports:
    #      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    networks:
      - airline

  airline-search:
    image: elasticsearch:7.17.21
    container_name: airline-search
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms1g -Xmx4g"
    networks:
      - airline
